### ISSUE TITLE
[ci] Add issues workflow labels

### ISSUE THREAD

**Issue by zhicheng-ning** [zhicheng-ning/Test-Hypercrx-CI#1]
### Description

mark the status of the issue as pending handle (contributor should reply) or pending feedback (issue author should reply)

**Comment by zhicheng-ning** [comment]
Hello CI

**Comment by tyn1998** [comment]
hello~

**Comment by zhicheng-ning** [comment]
issue author comment1

**Comment by tyn1998** [comment]
yes

**Comment by zhicheng-ning** [comment]
issue author comment2

**Comment by zhicheng-ning** [comment]
issue author comment 3

**Comment by tyn1998** [comment]
这个功能是有意义的，menbotics应该是没有的。

**Comment by tyn1998** [comment]
![image](https://user-images.githubusercontent.com/32434520/195251820-1c5174b3-88a7-4156-9e1a-62cb34424276.png)

但是事件多了，看起来有点乱

**Comment by zhicheng-ning** [comment]
仅区分 issue author comment 和 other comment，只有相邻两条评论是分属于上述两类评论时才会触发

**Comment by tyn1998** [comment]
志成，这个ci我觉得不错的，还可以改进的地方是label的颜色做个区分，然后label的名称再改一下更容易能一下子就能区分两类角色。你在hypercrx仓库里回我一下，我再comment~

**Comment by zhicheng-ning** [comment]
> 但是事件多了，看起来有点乱

一问一答的时候确实会显得消息有点多，但是按照业务逻辑来说，好像也应该是这样，想想看有什么可以优化逻辑处理地方

**Comment by tyn1998** [comment]
这个功能你是在别的仓库学到的吗

**Comment by zhicheng-ning** [comment]
BINGO

**Comment by zhicheng-ning** [comment]
@tyn1998 try comment here

**Comment by tyn1998** [comment]
hello

**Comment by xgdyp** [comment]
hello

**Comment by zhicheng-ning** [comment]
It seems that doesn't influence the order the event show in timeline.

**Comment by tyn1998** [comment]
是的，看出来惹
